env:
  browser: true
  es6: true

parserOptions:
  ecmaVersion: 2017
  sourceType: module

rules:
  func-call-spacing: error
  no-trailing-spaces: error
  space-before-blocks: error
  space-before-function-paren: [error, never]
  space-in-parens: [error, always]
