env:
  browser: true
  es6: true

parserOptions:
  ecmaVersion: 2017
  sourceType: module

rules:
  # http://eslint.org/docs/rules/#possible-errors
  no-cond-assign: error
  no-control-regex: error
  no-debugger: error
  no-dupe-args: error
  no-dupe-keys: error
  no-duplicate-case: error
  no-empty-character-class: error
  no-empty: error

  func-call-spacing: error
  no-trailing-spaces: error
  space-before-blocks: error
  # conflicts with beautifier
  # space-before-function-paren: [error, never]
  space-in-parens: [error, always]
